CC = gcc
CFLAGS = -Wall -g

# Archivos fuente y objetos
SRC = matrizm.c modulo.c
OBJ = $(SRC:.c=.o)

# Ejecutable
TARGET = programa

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJ)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)

run: $(TARGET)
	./$(TARGET)
	
#make        # Compila el programa
#make run    # Ejecuta el programa
#make clean  # Limpia los archivos generados